"""Phase 1 acceptance test — runs the 5 commands the user asked
for (/health, /tasks, /result, supervisorctl status, hermes-task list)
and writes the output to docs/phase1_acceptance_<TS>.md.

Run:
    .venv/bin/python tests/phase1_acceptance.py
"""
import os
import subprocess
import time
from datetime import datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
os.chdir(ROOT)
OUT_DIR = os.path.join(ROOT, "docs")
os.makedirs(OUT_DIR, exist_ok=True)
TS = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
OUT = os.path.join(OUT_DIR, f"phase1_acceptance_{TS}.md")


def _read_env():
    with open(os.path.join(ROOT, ".env")) as f:
        env = {}
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def run(cmd, env=None, **kw):
    """Run a shell command and return (returncode, stdout, stderr)."""
    proc = subprocess.run(
        cmd, shell=True, capture_output=True, text=True, env=env, **kw
    )
    return proc.returncode, proc.stdout, proc.stderr


def main():
    env = _read_env()
    # Unset any env var the shell might inject that breaks python.
    clean = dict(os.environ)
    for k in ("HERMES_API_KEY", "GPT_BRIDGE_API_KEY"):
        if k in clean:
            clean.pop(k, None)
    clean.update(env)  # env file is authoritative

    KEY = env.get("GPT_BRIDGE_API_KEY", "")
    out = []
    out.append(f"# Phase 1 驗收指令輸出 — {datetime.utcnow().isoformat()}Z\n")
    out.append(f"_Generated by `tests/phase1_acceptance.py` on host "
               f"`{subprocess.check_output('hostname').decode().strip()}`._\n")
    out.append("\n環境：\n")
    out.append(f"- Bridge port: `127.0.0.1:8787`")
    out.append(f"- Hermes: 8642")
    out.append(f"- API key: {len(KEY)} chars\n")

    # ------------------------------------------------------------------
    # 1) /health
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 1) `GET /health`\n")
    out.append("```bash\ncurl -sS -H \"Authorization: Bearer $KEY\" http://127.0.0.1:8787/health\n```\n")
    rc, so, se = run(
        f"curl -sS -H 'Authorization: Bearer {KEY}' http://127.0.0.1:8787/health",
        env=clean,
    )
    out.append(f"```json\n{so}\n```\n")

    # ------------------------------------------------------------------
    # 2) /tasks
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 2) `GET /tasks`\n")
    out.append("```bash\ncurl -sS -H \"Authorization: Bearer $KEY\" http://127.0.0.1:8787/tasks?limit=5\n```\n")
    rc, so, se = run(
        f"curl -sS -H 'Authorization: Bearer {KEY}' 'http://127.0.0.1:8787/tasks?limit=5'",
        env=clean,
    )
    # Try to pretty-print as YAML
    try:
        import json
        out.append("```json\n" + json.dumps(json.loads(so), indent=2) + "\n```\n")
    except Exception:
        out.append(f"```\n{so}\n```\n")

    # ------------------------------------------------------------------
    # 3) /result
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 3) `GET /result`\n")
    out.append("```bash\ncurl -sS -H \"Authorization: Bearer $KEY\" http://127.0.0.1:8787/tasks/TASK-20260707-0016/result\n```\n")
    rc, so, se = run(
        f"curl -sS -H 'Authorization: Bearer {KEY}' 'http://127.0.0.1:8787/tasks/TASK-20260707-0016/result'",
        env=clean,
    )
    try:
        import json
        out.append("```json\n" + json.dumps(json.loads(so), indent=2, default=str) + "\n```\n")
    except Exception:
        out.append(f"```\n{so}\n```\n")

    # ------------------------------------------------------------------
    # 4) supervisorctl status
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 4) `supervisorctl status`\n")
    out.append("```bash\nsudo supervisorctl --serverurl=unix:///tmp/supervisor.sock status\n```\n")
    rc, so, se = run(
        "sudo -n supervisorctl --serverurl=unix:///tmp/supervisor.sock status 2>&1 || supervisorctl --serverurl=unix:///tmp/supervisor.sock status 2>&1",
        env=clean,
    )
    out.append(f"```\n{so}{se}\n```\n")

    # ------------------------------------------------------------------
    # 5) hermes-task list
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 5) `hermes-task list`\n")
    out.append("```bash\n.venv/bin/python cli/hermes_task.py list --limit 10\n```\n")
    rc, so, se = run(
        "env -u HERMES_API_KEY .venv/bin/python cli/hermes_task.py list --limit 10",
        env=clean,
    )
    out.append(f"```\n{so}\n```\n")

    # ------------------------------------------------------------------
    # Phase 2 bonus — /stats/usage + reaper snapshot
    # ------------------------------------------------------------------
    out.append("\n---\n\n## 6) `GET /stats/usage?period=today` (Phase 2 P4)\n")
    out.append("```bash\ncurl -sS -H \"Authorization: Bearer $KEY\" http://127.0.0.1:8787/stats/usage?period=today\n```\n")
    rc, so, se = run(
        f"curl -sS -H 'Authorization: Bearer {KEY}' 'http://127.0.0.1:8787/stats/usage?period=today'",
        env=clean,
    )
    try:
        import json
        out.append("```json\n" + json.dumps(json.loads(so), indent=2, default=str) + "\n```\n")
    except Exception:
        out.append(f"```\n{so}\n```\n")

    out.append("\n---\n\n## 7) `hermes-task usage --today`\n")
    out.append("```bash\n.venv/bin/python cli/hermes_task.py usage --today\n```\n")
    rc, so, se = run(
        "env -u HERMES_API_KEY .venv/bin/python cli/hermes_task.py usage --today",
        env=clean,
    )
    out.append(f"```\n{so}\n```\n")

    # Write.
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
